################################ 
# This template is built to work with gitlab CI/CD setup, as detailed at following link:
# https://toronto.atlassian.net/wiki/spaces/EISTS/pages/514850829/How+to+enable+GitLab+CI+EIS+flavour
################################
include:
  - project: 'devops/gitlab-pipelines'
    ref: REL-2.2
    file: '/templates/ast-ci-template.yml'

default:
  tags: ['docker']

variables:
  LONG_LIVED_BRANCHES: /master/ # only changes in long-lived will be versioned
  THE_NAME: static-web  # used to name deploy package etc.
  THE_VERSION: 1.0  # only major.minor part will be used for tagging

sast: # Static Application Security Test (Whitebox)
  extends: .eis_sonar_scan 
  variables:
    SONAR_SRC: '.'    # source folder to be scanned by sonarqube

.dast: # Dynamic Application Security Test (Blackbox)
  extends: .eis_zap_scan
  variables:
    ZAP_URL: https://portal.cc.toronto.ca
      
      
